(sec-matrices-in-python)=
# Matrices in Python

The theory of quantum mechanics is based on linear algebra and mathematical objects such as vectors and operators are all expressed in abstract forms.  However, when we compute them in computers, classical or quantum, they must be expressed in a form the computers can understand. The use of *matrix recpresentation*  is the common approach. Most computer languages can natively handle matrices.  However, the python platform is not able to manage matrices.  There are many python libraries that can deal with matrices.  In this book, we use `numpy` libraries.  There is also a way to deal with matrix within the python platform using its native data type `dict`.  In this chapter, I introduce how to express matrices python, namely

1. List (python platform)
2. ndarray class (numpy library)
3. dict (python platform)

I also introduce some useful python functions related to matrices.

In the following matrix representation of a $n$-dimensional vector is written as

$$
|v\rangle \doteq \begin{pmatrix} v_0 & v_1 & \cdots & v_{n-1} \end{pmatrix}
$$

and a $n\times n$ matrix as

$$
M = \begin{pmatrix}m_{0,0} & m_{0,1} & \cdots & m_{0,n-1} \\
m_{1,2} & m_{1,1} & \cdots & m_{1,n-1} \\
\vdots & \ddots & \ddots & \vdots \\
m_{n-1,0} & m_{n-1,1} & \cdots & m_{n-1,n-1} 
\end{pmatrix} .
$$

## Lists

A collection of data placed in square brackets, for example, $[v_0, v_1, v_2, v_3]$ is called `list` in python.
This is not a matrix in the mathematical sense since arithmetic operations are not defined for `list` objects.  Nevertheless, Qiskit uses it just for expressing a state vector but not for computation.  Mathematical operations on state vectors must be done with Qiskit modules.  There are many functions that take `list` object as input and generate an appropriate form of state vectors.  We will discuss them in the coming chapters.

_Remark:_  Python has a similar data structure called `tuple`. It is also a collection of data objects but it is immortal, meaning that you cannot edit the contents after it is created.  Therefore, we do not use it.

## Vectors as array

Python does not have native array or matrix object.  Qiskit uses `ndarray`  (or simply `array`) from `numpy` library.  Here array and matrix are the same thing.  In this book, we invoke numpy as

`import numpy as np`

We create an `array` object directly from `list` in python. Just put a `list` object into `array` function.  Then, the output is the desired array object.  For example, list

> x = [3,1,2]

cannot be used as vector since mathematica addition is not defined for it.  However,

> y = np.array([3,2,1])

is `ndarray` class object and mathematically it can be considered as vector.

The print out of `list` and `ndarray` appear the same.  Do not get confused.




---
**Example**  {numref}`%s <sec-matrices-in-python>`.1&nbsp; Let us create vector $\left(\cos(\pi/4),\sin(\pi/4) \right)$.



In [11]:
# load numpy
import numpy as np

# create a list
x = [np.cos(np.pi/4), np.sin(np.pi/4)]

# convert list to array
y = np.array(x)

# check the type of array and its content.
print("type of x = ", type(x))
print("content of x = ", x,"\n")
print("type of y = ", type(y))
print("content of y = ", y,"\n")

type of x =  <class 'list'>
content of x =  [0.7071067811865476, 0.7071067811865475] 

type of y =  <class 'numpy.ndarray'>
content of y =  [0.70710678 0.70710678] 



You can access to a component of array with index (python uses [... ] to specity indeces.)  Both `'list` and `array` gives the same value.

In [13]:
# find the second element in the array
# remember that python index always begins with 0
# hence index=1 corresponds to the second element. 
print("second element in x = ",x[1])
print("second element in y = ",y[1])

second element in x =  0.7071067811865475
second element in y =  0.7071067811865475


Now, we calculate $x+x$ and $y+y$.  Notice that the sum of `list` data just concatenate two lists.  On the other hand, $y+y$ is arithmetic addition.  Now you see the difference between `list` and `array`.

In [18]:
print("x+x = ",x+x)
print("y+y = ",y+y)

x+x =  [0.7071067811865476, 0.7071067811865475, 0.7071067811865476, 0.7071067811865475]
y+y =  [1.41421356 1.41421356]


## Matrices as array

You can create a matrix as `ndarray` in the same way as vectors.

In [32]:
import numpy as np

# nested list
a = [[1,2],[3,4]]

# convert it to 2x2 matrix
b = np.array([ [1,2],[3,4]])

# nexted list
print("list a = ",a,"\n")
# 2*a is not scalr multiplication
# it just doubles the number of elements
print("2 x list = ",2*a,"\n")

print("matrix b\n",b,"\n")
print(" 2 x matrix\n",2*b)

list a =  [[1, 2], [3, 4]] 

2 x list =  [[1, 2], [3, 4], [1, 2], [3, 4]] 

matrix b
 [[1 2]
 [3 4]] 

 2 x matrix
 [[2 4]
 [6 8]]


## Tensor product

If a state vector $|\alpha\rangle$ is in $m$-dimensional vector space and another vector $|\beta\rangle$ in $n$-dimensional vector space, the state vector of the combined vector space is given by tensor (Kronecker) product $|\alpha\rangle \otimes |\beta\rangle$ whose dimension is $mn$. The tensor product is a very ubiquitous operation in quantum computing.  `kron` function in numpy computes the tensor product. For example, `kron(a,b)` computes $a \otimes b$ where $a$ and $b$ are `ndarray`.

The following example computes $[1,1] \otimes [1,-1]$.  The output should be $[1,-1,1,-1]$.

In [3]:
# First, we create two state vectors.
a = np.array([1,1])
b = np.array([1,-1])

# [1,1]⊗[1,−1]
ab=np.kron(a,b )

print(ab)

[ 1 -1  1 -1]


## Computational basis

The dimension of the smallest vector space is two.  Hence, it is spanned by two vectors, $|0\rangle$ and $|1\rangle$. Their matrix representations are

$$
|0\rangle \doteq [1,0], \qquad |1\rangle \doteq [0,1]
$$

You can construct a basis set of a bigger vector space with dimension $2^n$ by tensor product.  For example, the 8-dimensional vector space has eight basis vectors

$$
|000\rangle = |0\rangle \otimes |0\rangle \otimes |0\rangle, \quad |001\rangle = 0\rangle \otimes |0\rangle \otimes |1\rangle, \quad \cdots \quad |111\rangle = |1\rangle \otimes |1\rangle \otimes |1\rangle
$$

The following example generates the matrix representation of $|010\rangle$.

In [4]:
# define the basis vectors for 2d
ket0 = [1,0]
ket1 = [0,1]

# construct a basis vector for 8d
ket010 = np.kron(ket0,np.kron(ket1,ket0))
print(ket010)

[0 0 1 0 0 0 0 0]


_Remarks_: Some modules in Qiskit calculate the tensor product in an easier way. You are encouraged to use Qiskit classes instead of numpy.

## Matrix as dictionary

In the above example, only one out of eight components have non-vanishing value.   However, even such a simple state, it is not simple to find out which basis vector the matrix represnting.  In addition, we are wasting memory by having so many zeros.  It is much easier to express the state vector in phython's dictionary.  The dictionary is a set of key-value pairs placed in curly brackets, {key1:val1, key2:val2, ... }. The keys can be any data type including `string`.  Unlike matrix representation, it is not necessary to keep a key whose value is zero.  Hence, we don't see unnecessary zeros.

To find out a coefficient, just ask the value associate with the key. Search a key in dictionary is very fast because python implements them using hash tables. If you ask to look for non-existing key, you will get an error message.

_Remark:_ The data in `Dictionary` is ordered.  When a new key is added, it is placed at the end.  (Dictionary was unordered in python 3.6 and earlier.)

In the following example, we consider 16-dimensional vector space.  There are 16 computational basis vectors with four indexes. We create a state vector $\left(|0011\rangle + |0101\rangle \right)/\sqrt{2}$ in dictionary format.  Only two keys '0011' and '0101' have non-zero value, $\frac{1}{\sqrt{2}}$ and all other elements are zero.  Hence, we store only two elements in the dictionary. There are two ways to construct the dictionary, making the whole dictionary in one step and adding keys one by one.  We show the both.

In [5]:
# store (|0011>+|0101>)/sqrt(2) in dictionary

# direct method
psi={'0011':1/np.sqrt(2), '0101':1/np.sqrt(2)}
# check the type of variable and its content.
print("type = ",type(psi))
print("number of keys =", len(psi))
print("conent = ", psi,"\n")

type =  <class 'dict'>
number of keys = 2
conent =  {'0011': 0.7071067811865475, '0101': 0.7071067811865475} 



You can construct a dictionary key by key.

In [6]:
# create empty dictionary
psi = dict()
# add key one by one
psi['0011'] = 1/np.sqrt(2)
psi['0101'] = 1/np.sqrt(2)
# check the type of variable and its content.
print("type = ",type(psi))
print("number of keys =", len(psi))
print("conent = ", psi,"\n")

type =  <class 'dict'>
number of keys = 2
conent =  {'0011': 0.7071067811865475, '0101': 0.7071067811865475} 



In [7]:
# find a coefficient to |11>
print(psi['0101'])

0.7071067811865475


You can enter a key with zero value.  Dictionary will keep it as shown below.

In [8]:
# adding a key with zero value
psi['1111']=0
print("number of keys =", len(psi))
print("conent = ", psi,"\n")

number of keys = 3
conent =  {'0011': 0.7071067811865475, '0101': 0.7071067811865475, '1111': 0} 



In [9]:
# adding another key which will be placed at the end in the dictionary
# note that '0000' is the lsat one (recall that '0000' is the first element in the matrix.)
psi['0000']=0
print("number of keys =", len(psi))
print("conent = ", psi,"\n")

number of keys = 4
conent =  {'0011': 0.7071067811865475, '0101': 0.7071067811865475, '1111': 0, '0000': 0} 



:::{admonition}  Summary
:class: seealso

The following objects and methods are useed to construct state vectors in a numerical form.

* `list` - native python data structure:  [Python references: list](https://www.w3schools.com/python/python_lists.asp)
* `dictionary` - native python data structure: [Python references: dictionary](https://www.w3schools.com/python/python_dictionaries.asp)
* `array` - a class in `Numpy` module:  [Numpy references: ndarray](https://numpy.org/doc/stable/reference/arrays.ndarray.html)  
* `kron` - a function in `Numpy` module: 
[Numpy references: kron](https://numpy.org/doc/stable/reference/generated/numpy.kron.html)

:::

:::{admonition}  Suggested readings
:class: seealso


* T. E. Oliphant: _Guide to Numpy_ (Continuum Press, 2015)
* A. B. Downey: _Think Python_ 2nd ed. (O'REILLY, 2016)
                                        
:::